--------------------------------------------------------------------------------
-- hat_tiling.lua
--
-- Lazy, deterministic generator for the "hat" aperiodic monotile tiling
-- (Smith, Myers, Kaplan & Goodman-Strauss, 2023), shaped for use inside a
-- Factorio mod.
--
-- Design:
--   * The tiling is defined by a substitution system on four metatiles
--     H, T, P, F with inflation factor phi^2 in length (phi^4 in area).
--   * Rather than materialising the whole tiling, we keep only a root
--     supertile and recurse down it per chunk, pruning branches whose
--     bounding circle cannot intersect the chunk.
--   * Fully deterministic: no RNG, so multiplayer-safe with no state to sync.
--
-- TWO THINGS YOU MUST FILL IN (marked TODO below):
--   1. RULES       - the substitution geometry
--   2. METATILE    - the hat placements inside each level-0 metatile
--
-- Do NOT try to re-derive these from the figures in the paper. Craig Kaplan's
-- reference implementation (hatviz, github.com/isohedral/hatviz) contains them
-- as explicit transformation matrices; port those, and check its licence
-- before shipping.
--------------------------------------------------------------------------------

local M = {}

local PHI      = (1 + math.sqrt(5)) / 2
local INFLATE  = PHI * PHI            -- ~2.618, length scale per level
local SQRT3    = math.sqrt(3)

--------------------------------------------------------------------------------
-- Affine transforms, stored as a flat 6-tuple:
--   {a, b, c,
--    d, e, f}   maps (x, y) -> (a*x + b*y + c, d*x + e*y + f)
--------------------------------------------------------------------------------

local IDENTITY = {1, 0, 0, 0, 1, 0}

local function mul(A, B)
  return {
    A[1]*B[1] + A[2]*B[4],  A[1]*B[2] + A[2]*B[5],  A[1]*B[3] + A[2]*B[6] + A[3],
    A[4]*B[1] + A[5]*B[4],  A[4]*B[2] + A[5]*B[5],  A[4]*B[3] + A[5]*B[6] + A[6],
  }
end

local function apply(A, x, y)
  return A[1]*x + A[2]*y + A[3],
         A[4]*x + A[5]*y + A[6]
end

-- Uniform scale factor of a transform. The substitution uses only rotations,
-- reflections and uniform scaling, so this is well defined.
local function scale_of(A)
  return math.sqrt(math.abs(A[1]*A[5] - A[2]*A[4]))
end

local function rot(theta)
  local c, s = math.cos(theta), math.sin(theta)
  return {c, -s, 0, s, c, 0}
end

local function translate(x, y)  return {1, 0, x, 0, 1, y} end
local function scale(k)         return {k, 0, 0, 0, k, 0} end
local function reflect_x()      return {-1, 0, 0, 0, 1, 0} end

--------------------------------------------------------------------------------
-- 1. Hat outline, in kite-grid units.
--
-- The hat is eight kites of the [3.4.6.4] Laves tiling, so every vertex sits
-- on a lattice generated by 1.5 and sqrt(3)/2. VERIFY these coordinates against
-- hatviz before trusting them; the winding and starting vertex matter for the
-- point-in-polygon test below.
--------------------------------------------------------------------------------

local HAT_OUTLINE = {
  {  0.0,  0.0        },
  { -1.5, -0.5*SQRT3  },
  {  0.0, -1.0*SQRT3  },
  {  1.5, -0.5*SQRT3  },
  {  3.0, -1.0*SQRT3  },
  {  4.5, -0.5*SQRT3  },
  {  3.0,  0.0        },
  {  3.0,  1.0*SQRT3  },
  {  1.5,  1.5*SQRT3  },
  {  0.0,  1.0*SQRT3  },
  {  0.0,  2.0*SQRT3  },
  { -1.5,  2.5*SQRT3  },
  { -3.0,  2.0*SQRT3  },
  { -3.0,  1.0*SQRT3  },
}

-- Conservative circumradius of the outline about its own origin.
local HAT_RADIUS = (function()
  local r = 0
  for _, p in ipairs(HAT_OUTLINE) do
    r = math.max(r, math.sqrt(p[1]*p[1] + p[2]*p[2]))
  end
  return r
end)()

--------------------------------------------------------------------------------
-- 2. TODO: hats inside each level-0 metatile.
--
--   H: 4 hats (one of them reflected -- the "anti-hat")
--   T: 1 hat
--   P: 2 hats
--   F: 2 hats
--
-- Each entry is { reflected = bool, xform = <affine> }.
--------------------------------------------------------------------------------

local METATILE = {
  H = {
    -- { reflected = false, xform = mul(translate(?, ?), rot(?)) },
    -- { reflected = false, xform = ... },
    -- { reflected = false, xform = ... },
    -- { reflected = true,  xform = mul(..., reflect_x()) },
  },
  T = {},
  P = {},
  F = {},
}

--------------------------------------------------------------------------------
-- 3. TODO: substitution rules.
--
-- Each child transform must already include the 1/phi^2 downscale, so that
-- composing parent * child keeps everything in the parent's coordinate frame.
--------------------------------------------------------------------------------

local RULES = {
  H = {
    -- { "H", <affine> }, { "H", <affine> }, { "H", <affine> },
    -- { "T", <affine> },
    -- { "F", <affine> }, { "F", <affine> }, { "F", <affine> },
  },
  T = {
    -- { "H", <affine> },
  },
  P = {},
  F = {},
}

-- Circumradius of each level-0 metatile about its own origin, in the same
-- kite-grid units as HAT_OUTLINE. Fill in once METATILE is populated; these
-- only need to be upper bounds, and being generous just costs a little pruning.
local METATILE_RADIUS = {
  H = 4 * HAT_RADIUS,
  T = 2 * HAT_RADIUS,
  P = 3 * HAT_RADIUS,
  F = 3 * HAT_RADIUS,
}

--------------------------------------------------------------------------------
-- Lazy traversal
--
-- Walks the supertile tree from the root, emitting only hats that could touch
-- the query box. Cost is proportional to the output, not to the tiling size.
--------------------------------------------------------------------------------

local function circle_misses_box(cx, cy, r, box)
  -- Distance from circle centre to the axis-aligned box.
  local dx = math.max(box.left - cx, 0, cx - box.right)
  local dy = math.max(box.top  - cy, 0, cy - box.bottom)
  return dx*dx + dy*dy > r*r
end

-- shape: "H" | "T" | "P" | "F"
-- xform: accumulated transform from this node's frame to world space
-- level: remaining substitution depth (0 = expand into hats)
-- box:   {left, top, right, bottom} in world space
-- out:   accumulator
local function descend(shape, xform, level, box, out)
  local k  = scale_of(xform)
  local cx, cy = apply(xform, 0, 0)
  local r  = METATILE_RADIUS[shape] * k * (INFLATE ^ level)

  if circle_misses_box(cx, cy, r, box) then return end

  if level == 0 then
    for _, hat in ipairs(METATILE[shape]) do
      local hx = mul(xform, hat.xform)
      local px, py = apply(hx, 0, 0)
      if not circle_misses_box(px, py, HAT_RADIUS * scale_of(hx), box) then
        out[#out+1] = { xform = hx, reflected = hat.reflected }
      end
    end
    return
  end

  for _, child in ipairs(RULES[shape]) do
    descend(child[1], mul(xform, child[2]), level - 1, box, out)
  end
end

--------------------------------------------------------------------------------
-- Public API
--------------------------------------------------------------------------------

-- Tiles per kite-grid unit. Pick this so one hat spans roughly 16-24 Factorio
-- tiles: smaller and the square-tile rasterisation looks like noise, larger and
-- the aperiodicity stops being visible at play scale.
M.UNIT = 4.0

-- Depth of the root supertile. Each level multiplies covered area by ~6.854.
-- Level 8 from an H root covers a very large map; raise it if players reach the
-- edge, since nothing is precomputed and the cost is only in the descent.
M.LEVELS = 8

M.root_shape = "H"

local function root_xform()
  return mul(translate(0, 0), scale(M.UNIT))
end

--- Returns the hats overlapping an axis-aligned world-space box.
-- @param box {left=, top=, right=, bottom=} in Factorio tile coordinates
-- @return array of { xform = <affine>, reflected = bool }
function M.hats_in_box(box)
  local out = {}
  descend(M.root_shape, root_xform(), M.LEVELS, box, out)
  return out
end

--- World-space polygon for one hat.
function M.hat_polygon(hat)
  local poly = {}
  for i, p in ipairs(HAT_OUTLINE) do
    local x, y = apply(hat.xform, p[1], p[2])
    poly[i] = {x = x, y = y}
  end
  return poly
end

--- Stable identity for a hat, for keying colours, ownership, resources, etc.
-- Quantised so floating-point drift cannot produce two ids for one hat.
function M.hat_id(hat)
  local x, y = apply(hat.xform, 0, 0)
  return string.format("%.3f:%.3f", x, y)
end

--------------------------------------------------------------------------------
-- Rasterisation: which hat covers a given Factorio tile?
--------------------------------------------------------------------------------

local function point_in_polygon(px, py, poly)
  local inside = false
  local n = #poly
  local j = n
  for i = 1, n do
    local a, b = poly[i], poly[j]
    if (a.y > py) ~= (b.y > py) then
      local t = (py - a.y) / (b.y - a.y)
      if px < a.x + t * (b.x - a.x) then inside = not inside end
    end
    j = i
  end
  return inside
end

--- Maps every tile in a chunk to the hat covering its centre.
-- @return table keyed "tx,ty" -> hat
function M.rasterise_chunk(cx, cy)
  local left, top = cx * 32, cy * 32
  local box = {left = left, top = top, right = left + 32, bottom = top + 32}

  local hats = M.hats_in_box(box)
  local polys = {}
  for i, hat in ipairs(hats) do polys[i] = M.hat_polygon(hat) end

  local result = {}
  for ty = top, top + 31 do
    for tx = left, left + 31 do
      local px, py = tx + 0.5, ty + 0.5
      for i = 1, #polys do
        if point_in_polygon(px, py, polys[i]) then
          result[tx .. "," .. ty] = hats[i]
          break
        end
      end
    end
  end
  return result
end

--------------------------------------------------------------------------------
-- Example: cosmetic overlay drawn per chunk.
--
-- Check draw_polygon's current signature against the online API docs -- the
-- rendering API was reworked in 2.0 and returns LuaRenderObject now.
--------------------------------------------------------------------------------

function M.draw_chunk(surface, cx, cy)
  local left, top = cx * 32, cy * 32
  local hats = M.hats_in_box{
    left = left, top = top, right = left + 32, bottom = top + 32,
  }

  for _, hat in ipairs(hats) do
    local poly = M.hat_polygon(hat)
    local verts = {}
    for i, p in ipairs(poly) do verts[i] = {target = p} end

    rendering.draw_polygon{
      surface = surface,
      vertices = verts,
      color = hat.reflected and {0, 0.45, 0.8, 0.5} or {0.55, 0.78, 0.92, 0.35},
      draw_on_ground = true,
    }
  end
end

return M