"""Emit Lua data files for the tiling core.

WHY DOUBLES, NOT EXACT INTEGERS
-------------------------------
An earlier design carried the rules as exact integers in Z[phi][sqrt3]. That
was a mistake, and it came from conflating two different things.

The desync risk in Factorio is math.sin / math.cos / pow, whose libm
implementations genuinely differ across platforms. But IEEE-754 requires
+ - * / and sqrt to be CORRECTLY ROUNDED, so they are bit-identical everywhere;
Lua's interpreter runs each as its own VM instruction, so no compiler FMA
contraction can fuse them, and Factorio 2.0 is x86-64 only, so there is no x87
80-bit excess precision either. Doubles are exactly as deterministic as
integers here. They are only less accurate -- and measurably, that does not
matter:

    depth  coverage      relative error   absolute error
      8      26,660 t      5.7e-16          8e-12 tiles
     10     183,419 t      4.3e-16          7e-11 tiles
     12   1,194,588 t      5.3e-16          4e-10 tiles

Relative error sits at machine epsilon and does not grow with depth. Depth 12
covers the whole Factorio map with an error of four ten-billionths of a tile.

Exact integers, by contrast, could not reach past depth 4: level-6 rule
numerators are 1.4e14, so one composition produces a raw product near 1e28,
far past 2^53, and cross-reduction cannot help (operand gcd is 1 -- the
cancellation is additive, not multiplicative).

The exact arithmetic remains where it belongs: offline, in this pipeline,
deriving the rules and proving them correct. Only the VALUES ship.
"""
from __future__ import annotations

import math
import pathlib

from tools.field import K
from tools.geometry import HAT_OUTLINE
from tools.substitution import levels
from tools.verify import verify_all

# Depth 12 covers ~1.19e6 tiles at the default scale, i.e. the whole map.
MAX_LEVEL = 12
ROOT = pathlib.Path(__file__).resolve().parents[1]
HEADER = "-- GENERATED by tools/emit_lua.py -- DO NOT EDIT\n"

PHI = (1 + math.sqrt(5)) / 2
SQRT3 = math.sqrt(3)


def _f(k: K) -> float:
    """Exact ring element -> the double Lua will hold. Rounded exactly once."""
    return k.to_float()


def _num(v: float) -> str:
    """%.17g round-trips a double exactly."""
    return "%.17g" % v


def _hat_circumradius() -> float:
    return max(math.hypot(*p.to_float()) for p in HAT_OUTLINE)


def _prune_radius(mt) -> float:
    """Bounding radius for a metatile's whole SUBTREE of hats.

    Two corrections over the bare outline radius, both of which would otherwise
    drop hats silently:

    * Hats straddle metatile boundaries -- they are not contained by the
      outline -- so allow a full hat diameter of overhang.
    * construct_metatiles GROWS the outlines each level, so this is per level
      and must never be treated as a constant.
    """
    worst = max(math.hypot(*p.to_float()) for p in mt.outline)
    return worst + 2.0 * _hat_circumradius()


def emit_rules(path):
    lv = levels(MAX_LEVEL)
    out = [HEADER, "return {\n  max_level = %d,\n  levels = {\n" % MAX_LEVEL]
    for i, shapes in enumerate(lv):
        out.append("    [%d] = {\n" % i)
        for name in ("H", "T", "P", "F"):
            out.append("      %s = {\n" % name)
            for ch in shapes[name].children:
                label = ch.geom if isinstance(ch.geom, str) else ch.geom.label
                vals = ", ".join(_num(_f(k)) for k in ch.xf.m)
                out.append('        { shape = "%s", xf = { %s } },\n' % (label, vals))
            out.append("      },\n")
        out.append("    },\n")
    out.append("  },\n  radius = {\n")
    for i, shapes in enumerate(lv):
        rad = ", ".join("%s = %s" % (n, _num(_prune_radius(shapes[n]) * 1.05))
                        for n in ("H", "T", "P", "F"))
        out.append("    [%d] = { %s },\n" % (i, rad))
    out.append("  },\n}\n")
    path.write_text("".join(out))


def emit_geometry(path):
    pts = ",\n    ".join("{ %s, %s }" % (_num(x), _num(y))
                         for x, y in (p.to_float() for p in HAT_OUTLINE))
    path.write_text(HEADER + "return {\n  vertices = %d,\n  circumradius = %s,\n"
                    "  outline = {\n    %s\n  },\n}\n"
                    % (len(HAT_OUTLINE), _num(_hat_circumradius()), pts))


def main():
    errs = verify_all(2)
    if errs:
        raise SystemExit("verification failed:\n" + "\n".join(errs))
    (ROOT / "data").mkdir(exist_ok=True)
    emit_rules(ROOT / "data" / "hat_rules.lua")
    emit_geometry(ROOT / "data" / "hat_geometry.lua")
    print(f"wrote data/hat_rules.lua (levels 0..{MAX_LEVEL}) and data/hat_geometry.lua")


if __name__ == "__main__":
    main()
