"""Emit Lua data files containing only integer literals.

CEILING: the per-level substitution rules are exact rationals converging on
irrational limits, so their numerators and denominators blow up with level:

    level 6:  num 1.4e14   OK
    level 7:  num 1.7e16   exceeds 2^53 = 9.0e15

Lua 5.2 has no integer subtype, so an emitted literal above 2^53 is not
representable exactly. MAX_LEVEL is therefore 6 until tools/exactify.py finds
the limiting phi-proportioned metatiles, where one rule set with small exact
coefficients works at every depth. Every emitted value is asserted below 2^53.
"""
from __future__ import annotations

import math
import pathlib

from tools.field import K
from tools.geometry import HAT_OUTLINE
from tools.substitution import levels
from tools.verify import verify_all

MAX_LEVEL = 6
LIMIT = 2 ** 53
ROOT = pathlib.Path(__file__).resolve().parents[1]
HEADER = "-- GENERATED by tools/emit_lua.py -- DO NOT EDIT\n"


def _ints(k: K, den: int):
    scaled = k * K.from_int(den)
    assert scaled.is_integral(), f"non-integral after scaling by {den}: {k}"
    out = scaled.numerators()
    for v in out:
        assert abs(int(v)) < LIMIT, f"coefficient {v} exceeds 2^53"
    return tuple(int(v) for v in out)


def _xf_ints(xf, den):
    out = []
    for k in xf.m:
        out.extend(_ints(k, den))
    return out


def _hat_circumradius() -> float:
    return max(math.hypot(*p.to_float()) for p in HAT_OUTLINE)


def _prune_radius(mt) -> float:
    """Bounding radius for a metatile's whole SUBTREE of hats.

    Two corrections over the bare outline radius, both of which would otherwise
    drop hats silently:

    * Hats straddle metatile boundaries -- they are not contained by the
      outline -- so allow a full hat diameter of overhang.
    * construct_metatiles GROWS the outlines each level, so this is per level
      and must never be treated as a constant.
    """
    worst = 0.0
    for p in mt.outline:
        x, y = p.to_float()
        worst = max(worst, math.hypot(x, y))
    return worst + 2.0 * _hat_circumradius()


def emit_rules(path):
    lv = levels(MAX_LEVEL)
    out = [HEADER, "return {\n  max_level = %d,\n  levels = {\n" % MAX_LEVEL]
    for i, shapes in enumerate(lv):
        out.append("    [%d] = {\n" % i)
        for name in ("H", "T", "P", "F"):
            mt = shapes[name]
            out.append("      %s = {\n" % name)
            for ch in mt.children:
                den = ch.xf.denominator()
                assert den < LIMIT, f"denominator {den} exceeds 2^53"
                label = ch.geom if isinstance(ch.geom, str) else ch.geom.label
                nums = ", ".join(str(n) for n in _xf_ints(ch.xf, den))
                out.append('        { shape = "%s", den = %d, xf = { %s } },\n'
                           % (label, den, nums))
            out.append("      },\n")
        out.append("    },\n")
    out.append("  },\n  radius = {\n")
    for i, shapes in enumerate(lv):
        rad = ", ".join("%s = %.9g" % (n, _prune_radius(shapes[n]) * 1.05)
                        for n in ("H", "T", "P", "F"))
        out.append("    [%d] = { %s },\n" % (i, rad))
    out.append("  },\n}\n")
    path.write_text("".join(out))


def emit_geometry(path):
    den = 2
    verts = []
    for p in HAT_OUTLINE:
        verts.append(_ints(p.x, den))
        verts.append(_ints(p.y, den))
    body = ",\n    ".join("{ %d, %d, %d, %d }" % v for v in verts)
    path.write_text(HEADER + "return {\n  den = %d,\n  vertices = %d,\n"
                    "  outline = {\n    %s\n  },\n}\n"
                    % (den, len(HAT_OUTLINE), body))


def main():
    errs = verify_all(2)
    if errs:
        raise SystemExit("verification failed:\n" + "\n".join(errs))
    (ROOT / "data").mkdir(exist_ok=True)
    emit_rules(ROOT / "data" / "hat_rules.lua")
    emit_geometry(ROOT / "data" / "hat_geometry.lua")
    print(f"wrote data/hat_rules.lua (levels 0..{MAX_LEVEL}) and data/hat_geometry.lua")


if __name__ == "__main__":
    main()
