"""Export a reference hat set that the Lua descent must reproduce exactly."""
from __future__ import annotations

import pathlib

from tools.field import K
from tools.geometry import Pt, Xf
from tools.hatviz_port import MetaTile
from tools.substitution import levels

ROOT = pathlib.Path(__file__).resolve().parents[1]
DEPTH = 3
ORIGIN = Pt(K.ZERO, K.ZERO)


def walk(mt: MetaTile, acc: Xf, path, out):
    for i, ch in enumerate(mt.children):
        xf = acc.mul(ch.xf)
        p = path + [i]
        if isinstance(ch.geom, str):
            o = xf.apply(ORIGIN)
            out.append((p, o.x.to_float(), o.y.to_float(), xf.is_reflected()))
        else:
            walk(ch.geom, xf, p, out)


def main():
    out = []
    walk(levels(DEPTH)[DEPTH]["H"], Xf.identity(), [], out)
    out.sort(key=lambda r: r[0])
    lines = ["-- GENERATED by tools/export_golden.py -- DO NOT EDIT\n",
             "-- depth %d from an H root, identity transform, unit scale\n" % DEPTH,
             "return {\n"]
    for p, x, y, r in out:
        key = ",".join(str(i) for i in p)
        lines.append('  { path = "%s", x = %.12g, y = %.12g, reflected = %s },\n'
                     % (key, x, y, "true" if r else "false"))
    lines.append("}\n")
    d = ROOT / "spec" / "fixtures"
    d.mkdir(parents=True, exist_ok=True)
    (d / "golden_depth3.lua").write_text("".join(lines))
    print(f"wrote {len(out)} hats to spec/fixtures/golden_depth3.lua")


if __name__ == "__main__":
    main()
